name: GitHub Auto Builder For Blog

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 21 * * *'

env:
  TZ: Asia/Shanghai

jobs:        
  blog-cicd:
    name: Hexo build and deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"

      - name: Clone themes
        run: |
          git clone -b master https://github.com/fluid-dev/hexo-theme-fluid.git themes/fluid          

      - name: Cache Node Dependencies
        id: cache
        uses: actions/cache@v1
        with:
          path: .npm
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm init -y
          npm install hexo-cli -g
          npm install
          npm audit fix          

      - name: Generate files
        run: |
          hexo clean && hexo generate
          ls -la

      - name: Deploy blog
        run: |
          pwd  # 打印当前工作目录

          # 克隆你的 GitHub Pages 仓库到 deploy_git 目录
          git clone "https://${{ secrets.GH_REF }}" deploy_git

          # 切换到 deploy_git 目录
          cd ./deploy_git

          ls -al

          cp -r blog_source/ ./

          # 切换到 main 分支
          git checkout main


          # 配置 Git 用户信息
          git config --local user.email "your-email@example.com"  # 你的邮箱
          git config --local user.name "your-username"  # 你的用户名

          # 添加更改并提交
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"

          # 强制推送到 main 分支
          git push --force "https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}" main:main
